### ISSUE TITLE
Feature: Support for concurrent queries on Local Dev Server

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#103]
I was trying to run two queries at once, and noticed that the dev server was only returning data for one of them, the other one simply returning "null".

![image](https://user-images.githubusercontent.com/3979239/215991364-92721562-51b9-46c3-a8e6-5d6d00529cfb.png)

![image](https://user-images.githubusercontent.com/3979239/215991323-50fa8d4e-4ee1-42ef-a773-f62fb260f6ae.png)

**Comment by maoosi** [comment]
@Tenrys I've been working with GraphQL for years on dozen projects... And I actually had no idea you could run multiple queries at once this way 😄

I'll add it to the Roadmap and will have to dig around a bit to figure out how to fix this. Does it work fine when running multiple queries at once directly on AWS AppSync?

**Comment by Tenrys** [comment]
> Does it work fine when running multiple queries at once directly on AWS AppSync?

Yes, it does. It's easy to test this by adding multiple queries at once by expanding them on the AppSync query explorer, and with GraphQL Yoga.

**Comment by maoosi** [comment]
Will be released as part of `1.0.0-rc.6` (you can also try it now with `prisma-appsync@1.0.0-preview.6.7`).
