### ISSUE TITLE
(MongoDB) The ID field is required in the schema when it should be generated by the database

### ISSUE THREAD

**Issue by mikerudge** [maoosi/prisma-appsync#109]
When adding a model, the ID field should not be required in the create type. For example, this user model 

```prisma
model User {
    id            String    @id @default(auto()) @map("_id") @db.ObjectId
    name          String?
}
```

produces

```gql
input UserCreateInput {
    id: String! <-- ID should not be required here
    name: String
}
```

**Comment by maoosi** [comment]
Related to https://github.com/maoosi/prisma-appsync/issues/96. Fix is ready and will be released as part of [1.0.0-rc.6](https://github.com/maoosi/prisma-appsync/milestone/5).
