### ISSUE TITLE
pnpm test fails. Missing Prisma

### ISSUE THREAD

**Issue by DregondRahl** [maoosi/prisma-appsync#11]
import { PrismaClient, **Prisma** } from "@prisma/client";

Prisma is not exported when installed fresh. Only after the generator is run does it expose Prisma. But can't run generator without first building. Maybe this is more a prisma issue?

**Comment by maoosi** [comment]
Might be related to this? https://github.com/prisma/prisma/issues/6603

I'll add a `postinstall` script as suggested with the next release (later today), which will also resolve an issue I've introduced with 1.0.0-beta.52 in regards to accessing Prisma client from inside a custom resolver.

**Comment by maoosi** [comment]
I've just release [1.0.0-beta.53](https://github.com/maoosi/prisma-appsync/releases/tag/1.0.0-beta.53) with `postinstall`. Closing this issue for now, but let me know in case still present.

**Comment by maoosi** [comment]
I've actually had to rollback, as the new `postinstall` script was breaking installation. I will re-open the issue and investigate further.

**Comment by maoosi** [comment]
Should be resolved in [1.0.0-beta.56](https://github.com/maoosi/prisma-appsync/releases/tag/1.0.0-beta.56). Let me know in case still present.
