### ISSUE TITLE
Use Prisma-appsync in monorepo

### ISSUE THREAD

**Issue by edgehero** [maoosi/prisma-appsync#121]
currently in my project is use the monorepo https://nx.dev/ 
but when trying to prisma Prisma-appsync to aws with CDK i get 1001 compile errors. 
they happen when the docker runs esbuild

example of the error that im currently stuck on: 

```Bundling asset cdk/cdkDevelopmentFn/Code/Stage...
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions
```

is there a easy way to do this?

**Comment by maoosi** [comment]
Hey @edgehero, not sure how to help with so little details on your use case. Please share a minimal reproduction repo.

**Comment by maoosi** [comment]
Closing until further details.
