### ISSUE TITLE
Issue: shield rule on model with WhereUniqueInput results in error

### ISSUE THREAD

**Issue by jeremy-white** [maoosi/prisma-appsync#123]
Related to issue https://github.com/maoosi/prisma-appsync/issues/87 

In a new repository with Prisma-AppSync 1.0.0-rc.5 and Prisma 4.11.0

WIth the extendedWhereUnique preview feature enabled, a model defined as 

```
model User {
  id            String       @id @default(uuid())
  username      String       @unique 
}
```

and a shield rule of 
```
'{update,upsert,delete}User{,/**}': {
     rule: { id: identity?.sub },
     reason: ({ model }) => `${model} can only be modified by their owner.`,
 },
```

executing the mutation
```
mutation updateUser {
  updateUser(where: {id: "10eeced1-80a6-4551-801c-58a884e59c57"}, data: {username: "updated"}) {
    id
  }
}
```

results in the error 
```
  error: 'Prisma Client validation error. https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientvalidationerror',
  type: 'INTERNAL_SERVER_ERROR',
  code: 500,
  cause: PrismaClientValidationError: 
  Invalid `prisma.user.update()` invocation:
  
  {
    data: {
      username: 'jw'
    },
    where: {
      AND: [
        {
          id: '10eeced1-80a6-4551-801c-58a884e59c57'
        },
        {
          id: '10eeced1-80a6-4551-801c-58a884e59c57'
        }
      ]
    },
    select: {
      id: true
    }
  }
  
  Argument where of type UserWhereUniqueInput needs at least one argument and at least one argument for id. Available args are listed in green.
```

As a quick test I've changed the code here https://github.com/maoosi/prisma-appsync/blob/1d9b0f1dea83c1b0cb24be6e45acdcfc24d87607/packages/client/src/resolver.ts#L34

to be 

```
prismaArgs[operator] = {
    ...prismaArgs[operator],
    AND: [query[operator]],
}
```

Which allows everything to work as far as I can tell so far, but I'm sure there may be a better way to address it.

Am willing to work on it further and open a PR if that would be of help

**Comment by micklaw** [comment]
@maoosi I was wondering if it was worth me cloning this repo and potentially looking to resolve this as a collaborator, or does it tie in to a bigger story for you at the moment.

We are using this package in our production application, and this is now blocking us on our latest release. I more than happy to play around, just don't want to waste any time if you are aligned to this or have specific sights on what the solution should look like specifically?

**Comment by maoosi** [comment]
@micklaw Happy for you to open a PR.

I don't think the issue has anything to do with shield rules, but what suggested @jeremy-white is a good place to start:

> As a quick test I've changed the code here
> 
> [prisma-appsync/packages/client/src/resolver.ts](https://github.com/maoosi/prisma-appsync/blob/1d9b0f1dea83c1b0cb24be6e45acdcfc24d87607/packages/client/src/resolver.ts#L34)
> 
> Line 34 in [1d9b0f1](https://github.com/maoosi/prisma-appsync/commit/1d9b0f1dea83c1b0cb24be6e45acdcfc24d87607)
>
> to be
> 
> prismaArgs[operator] = {
>     ...prismaArgs[operator],
>     AND: [query[operator]],
> }

We just need to make sure it still works with broader use cases and with the `extendedWhereUnique` preview feature disabled.

**Comment by maoosi** [comment]
@micklaw all other tasks for the [1.0.0-rc.6 release milestone ](https://github.com/maoosi/prisma-appsync/milestone/5) are ready, so I might be able to work on this issue sometime this week. Are you still wanting to contribute, or should I take this one over?

**Comment by maoosi** [comment]
@all-contributors please add @jeremy-white for code.
