### ISSUE TITLE
Feature request: Adding a new GraphQL Subscription for ANY mutation (created/updated/deleted)

### ISSUE THREAD

**Issue by DregondRahl** [maoosi/prisma-appsync#13]
Sometimes we would need to listen for multiple events to update a record, for example, we need to update a value if something change been updated/deleted/created. 

Although we can listen to each separate event, would it make sense to have a catch all sort of logic?

**Comment by maoosi** [comment]
I can see a use case for this, though I would probably go with something like `onMutatedPost` to keep it consistent with the existing Subscriptions:

```
onCreatedPost
onUpdatedPost
onDeletedPost
```

**Comment by maoosi** [comment]
Implemented in [1.0.0-beta.58.2](https://github.com/maoosi/prisma-appsync/releases/tag/1.0.0-beta.58.2) (see `onMutatedPost` and `onMutatedManyPosts`).
