### ISSUE TITLE
@auth type public access

### ISSUE THREAD

**Issue by cipriancaba** [maoosi/prisma-appsync#138]
Currently when you set a `defaultDirective` there is no way of making a route available publicly. This might be by design, but it would be nice to be able to specify a model as being publicly accessible, maybe even on operation level

```
defaultDirective = "@auth(model: [{ allow: apiKey }])"
```

**Comment by maoosi** [comment]
AWS AppSync doesn't allow creating fully Public routes. In its current design, auth is mandatory using one of the 5 Authorization modes: https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html

Only the local dev server allow to entirely bypass Authorization. There is ongoing work happening to replace the current local dev server with `amplify-appsync-simulator` (see https://github.com/maoosi/prisma-appsync/discussions/130) - which would make the local dev server act closer to AWS AppSync defaults.

**Comment by cipriancaba** [comment]
Thanks for clarifying @maoosi
