### ISSUE TITLE
Local server does not take into account the data from the authorization token (AMAZON_COGNITO_USER_POOLS auth mode)

### ISSUE THREAD

**Issue by max-konin** [maoosi/prisma-appsync#139]
Hi
I see that some data such as username & sub is hardcoded. And claims is an empty object. And there is no way to influence it.
I think it would be logical to take this data from a real Cognito token. I sketched a simple solution here https://github.com/max-konin/prisma-appsync/commit/739e27b80277d3238ee912f18c54971ea5ebaaee

What do you think?

**Comment by maoosi** [comment]
@max-konin I think that's a great idea! Feel free to open a PR and I will include your contribution to the next release.

**Comment by maoosi** [comment]
Will be released as part of [1.0.0-rc.7](https://github.com/maoosi/prisma-appsync/milestone/6)
