### ISSUE TITLE
Feat: migrate local dev server to Amplify AppSync Simulator

### ISSUE THREAD

**Issue by maoosi** [maoosi/prisma-appsync#146]
Related issues that this feature will resolve:

- https://github.com/maoosi/prisma-appsync/issues/137
- https://github.com/maoosi/prisma-appsync/issues/112

Considerations:

- https://github.com/maoosi/prisma-appsync/pull/143

**Comment by maoosi** [comment]
Will be released as part of [1.0.0-rc.7](https://github.com/maoosi/prisma-appsync/milestone/6).

**Comment by cipriancaba** [comment]
Legend 💪
