### ISSUE TITLE
Document copying custom files if using the CDK

### ISSUE THREAD

**Issue by ryands17** [maoosi/prisma-appsync#2]
In the section for [Extending the API](https://prisma-appsync.vercel.app/guides/extending-api.html), if using the CDK we need to copy the `custom-schema.gql` and `custom-resolvers.yaml` in the folder so that `prisma generate` works properly.

Example code:

![image](https://user-images.githubusercontent.com/19697099/111633440-83b36a00-881b-11eb-87bb-88967edb6049.png)

I can add a PR for this if required :)

**Comment by maoosi** [comment]
Thanks, @ryands17 - that's something I forgot to mention indeed.

I've just pushed a new update to the docs, that include your [suggestion](https://prisma-appsync.vercel.app/guides/extending-api.html#%F0%9F%91%89-4-nodejs-function-bundler).
