### ISSUE TITLE
override field level resolver 

### ISSUE THREAD

**Issue by mikerudge** [maoosi/prisma-appsync#22]
Hey 

I am looking to have a custom resolver on single field but that lives outside of the resolvers function. I'l try to explain. 

Let's say the Prisma schema is this. 

```
model User {
  id                 String        @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name               String
```

Then else where in our CDK we have a service that wants to add in a `avatar` or something on the User

```graphql
extend type User {
	avatar: String
}
```

So far so good. 

Now what I want (I think) is for the prisma-appsync to not try to resolve `user.avatar` at all, because it is setup else where in the cdk. 

Simply excluding the resolver is not enough because when a query like 

```graphql
query {
	getUser {
		id
		name
		avatar  <--- this should not touch the prisma resolver and instead use the custom resolver setup outside.
	}
}
```

it will obviously try to find `avatar` from the prisma client, which doesn't exist in the database. 

Maybe something in the custom resolvers like: 

```
- typeName: User
  fieldName: avatar
  dataSource: ignore
```

**Comment by maoosi** [comment]
Adding such feature directly into the Generator might require quite lots of internal changes. Until then, there might be a way to achieve what you want using Prisma Client middleware as follow:

```typescript
app.prisma.$use(async (params, next) => {
    if (params.model == 'User') {
        for (const arg in params.args) {
            if (typeof params.args[arg]['avatar'] !== 'undefined') {
                delete params.args[arg]['avatar']
            }
        }

    }
    return next(params)
})
```

https://prisma-appsync.vercel.app/reference/client-api.html#prisma
https://www.prisma.io/docs/concepts/components/prisma-client/middleware
https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware

I haven’t tried it myself, so I can’t be 100% sure - but in theory, this should automatically delete the `avatar` field before querying data with Prisma Client.

Let me know if that works for your use case?

**Comment by mikerudge** [comment]
Was hoping to give this a go today but ran into some other issues. Will keep you updated! 

Thanks again!
