### ISSUE TITLE
Issue with relation If field is not null the input is required in mutation

### ISSUE THREAD

**Issue by maximilianorom77** [maoosi/prisma-appsync#26]
Hey!

I have a model Client that has a many to one relation with Tenant, here there is the model and the generated input for the createClient mutation:
As tenantId and Tenant cannot be null the generated input ClientCreateInput makes both fields required
```GraphQL
model Client {
  id       String @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  tenantId String @default(dbgenerated("uuid_generate_v4()")) @db.Uuid <--- both fields cannot be null
  Tenant   Tenant @relation(fields: [tenantId], references: [id])      <--- 
  User     User[]
}
```
```GraphQL
input ClientCreateInput {
    tenantId: String!                         <--- both fields are required
    Tenant: ClientTenantCreateRelationsInput! <--- passing both in a mutation to create a
    User: ClientUserCreateRelationsInput           Client leads to an exception
}
```

So if I only pass one I get this error
<img width="1022" alt="Screen Shot 2021-09-01 at 09 02 38" src="https://user-images.githubusercontent.com/58014752/131668836-aa310072-94b8-4ed4-9caa-c9b41bfea8c5.png">

And if I try passing both I get a timeout exertion and a hidden error message in Cloudwatch
<img width="1022" alt="Screen Shot 2021-09-01 at 09 05 43" src="https://user-images.githubusercontent.com/58014752/131668855-89faf199-60e0-4722-81a8-df33e29bc01c.png">

My "solution" was to make the fields nullable with the `?` mark 
```GraphQL
model Client {
  id       String @id  @default(dbgenerated("uuid_generate_v4()")) @db.Uuid 
  tenantId String? @default(dbgenerated("uuid_generate_v4()")) @db.Uuid <--- both fields are nullable
  Tenant   Tenant? @relation(fields: [tenantId], references: [id])      <--- 
  User     User[]
}
```
that way the input for those fields are optional
```GraphQL
input ClientCreateInput {
    tenantId: String                         <--- both fields are optional to pass in the mutation
    Tenant: ClientTenantCreateRelationsInput <--- just providing one is enough
    User: ClientUserCreateRelationsInput
}
```
And if I provide only the Tenant I am able to create the Client and connect with a Tenant
<img width="1017" alt="Screen Shot 2021-09-01 at 10 45 08" src="https://user-images.githubusercontent.com/58014752/131682698-06794bd8-6e34-4ed0-817a-b49aaedff834.png">

same if I provide the tenantId
<img width="1021" alt="Screen Shot 2021-09-01 at 10 50 59" src="https://user-images.githubusercontent.com/58014752/131683535-53c4d1e5-655b-4674-acda-070b6f397989.png">

making the field nullable in the model to make the input optional is not what I want, I would prefer a directive that let me set the field as not null and in the same time the input for the create mutation to be optional

**Comment by maoosi** [comment]
Thanks for reporting @maximilianorom77 - this should be fixed in the next release.
