### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by adamszeptycki** [maoosi/prisma-appsync#28]
I have a problem creating custom subscription.

I've created custom resolver (to create a resource) and I would like to add custom subscription for that.
It's not clear for me if I should do anything beside defining that in graphql schema?
Do I need to create custom resolver to handle that? Is that magically handled? Is there a chance to get some documentation or example for it?

**Comment by adamszeptycki** [comment]
@maoosi I've managed to solve my problem I would be to happy to add a "how to" to your docs if you just point me into right direction.

**Comment by maoosi** [comment]
Hey @adamszeptycki, happy to hear that you've solved your problem.

There is a section in the documentation dedicated to "Extending the API" (using custom resolvers) at [prisma-appsync.vercel.app/guides/extending-api](https://prisma-appsync.vercel.app/guides/extending-api.html).

Feel free to open a PR and contribute to the docs if you feel like something is missing or could be explained better.
