### ISSUE TITLE
Issue parsing prismaClientModels from auto-injected environment variable `PRISMA_APPSYNC_GENERATED_CONFIG`.

### ISSUE THREAD

**Issue by revmischa** [maoosi/prisma-appsync#30]
I'm running prisma-appsync on AWS lambda. It was running fine until I upgraded to using ES modules to enable tree shaking to reduce my bundle size.

After upgrading, I was able to get my lambda functions that use prisma working, using a [lambda layer](https://github.com/jetbridge/jetkit-cdk/blob/runtime-pkg-prismalayer/packages/cdk/src/cdk/lambda/prismaLayer.ts). When I use `prisma-appsync` from my lambda layer I get a strange error telling me 
```
    "errorType": "Error",
    "errorMessage": "@prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.\nIn case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
    "stack": [
        "Error: @prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.",
        "In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
        "    at new PrismaClient (/opt/nodejs/node_modules/.prisma/client/index.js:3:11)",
        "    at null.CustomPrismaClient (/node_modules/prisma-appsync/dist/prisma-appsync/index.js:2:70146)",
        "    at Object.PrismaAppSync (/node_modules/prisma-appsync/dist/prisma-appsync/index.js:2:70683)",
        "    at getApp (/be/ats/src/api/graphql/appSyncHandler.ts:20:15)",
        "    at Runtime.appSyncHandler (/be/ats/src/api/graphql/appSyncHandler.ts:39:15)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```
Which is odd because none of my other prisma-using lambda functions had this error, only my appsync handler function.

I tried bundling `prisma-appsync` with my lambda function and not getting it off the lambda layer. This results in a different error:
```
2021-10-03T21:01:53.329Z prisma:tryLoadEnv Environment variables not found at null
--
2021-10-03T21:01:53.331Z prisma:tryLoadEnv Environment variables not found at /packages/repo/prisma/.env
2021-10-03T21:01:53.331Z prisma:tryLoadEnv No Environment variables loaded
START RequestId: 45d0bddf-942d-4913-8484-3df79a763bb8 Version: $LATEST
2021-10-03T21:01:53.588Z prisma:tryLoadEnv Environment variables not found at null
2021-10-03T21:01:53.588Z prisma:tryLoadEnv Environment variables not found at /packages/repo/prisma/.env
2021-10-03T21:01:53.588Z prisma:tryLoadEnv No Environment variables loaded
2021-10-03T21:01:53.625Z prisma:client clientVersion: 3.1.1
2021-10-03T21:01:53.626Z prisma:client:libraryEngine internalSetup
2021-10-03T21:01:53.661Z	45d0bddf-942d-4913-8484-3df79a763bb8	TRACE	Starting appSyncHandler
2021-10-03T21:01:53.661Z	45d0bddf-942d-4913-8484-3df79a763bb8	ERROR	API [500]:  Issue parsing prismaClientModels from auto-injected environment variable `PRISMA_APPSYNC_GENERATED_CONFIG`.
2021-10-03T21:01:53.810Z	45d0bddf-942d-4913-8484-3df79a763bb8	ERROR	Invoke Error 	{     "errorType": "500",     "errorMessage": "Internal error.",     "errorInfo": "Internal Server Error",     "privateMessage": "Issue parsing prismaClientModels from auto-injected environment variable `PRISMA_APPSYNC_GENERATED_CONFIG`.",     "data": null,     "stack": [         "InternalError: Internal error.",         "    at Object.parseRequest (/node_modules/prisma-appsync/dist/prisma-appsync/index.js:2:43315)",         "    at Object.PrismaAppSyncAdapter (/node_modules/prisma-appsync/dist/prisma-appsync/index.js:2:41397)",         "    at Object.parseEvent (/node_modules/prisma-appsync/dist/prisma-appsync/index.js:2:70959)",         "    at Runtime.appSyncHandler (/be/ats/src/api/graphql/appSyncHandler.ts:44:9)",         "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"     ] }
```

Any suggestions?

**Comment by maoosi** [comment]
Hey @revmischa, the first error is coming from Prisma itself and usually refers to not having run `npx prisma generate`, or not having bundled some of the required `node_modules` dependencies with your Lambda function.

The second error is Prisma-AppSync specific. When running `npx prisma generate` Prisma-AppSync will inject an environment variable `PRISMA_APPSYNC_GENERATED_CONFIG` automatically at the top of the Prisma-AppSync generated Client (inside the file that is imported in your Lambda handler function via `import { PrismaAppSync } from './prisma/generated/prisma-appsync/client'`).

I’ve never tried using it inside a Lambda layer myself, but in both cases, I would suggest to:

1. Make sure that you run `npx prisma generate` before each deployment.
2. After that, make sure to include all relevant dependencies with your Lambda layer. I suggest you look at the [provided CDK Boilerplate](https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/boilerplate/cdk/index.ts#L97) - especially the `beforeBundling` and `afterBundling` functions. Note that the Boilerplate is using ESbuild via the [NodejsFunction CDK construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html).

**Comment by revmischa** [comment]
Thanks for the helpful info! I'm still trying to work out what's going on.
My NodejsFunction props look something like this: 
```
{
        memorySize: 1536,
        timeout: Duration.seconds(30),
        // bundling: { nodeModules: ["prisma-appsync", "@prisma/client"] },

        bundling: {
          externalModules: ["aws-sdk", "@prisma/engines"],
          commandHooks: {
            beforeInstall: () => [],
            afterBundling: () => [],
            beforeBundling(inputDir: string, outputDir: string): string[] {
              const prismaSchema = path.join(inputDir, "packages", "repo", "prisma", "schema.prisma")
              const customSchema = path.join(path.dirname(prismaSchema), "platform-resolvers.gql")
              const customResolvers = path.join(path.dirname(prismaSchema), "platform-resolvers.yaml")

              return [
                `cp ${prismaSchema} ${outputDir}`,
                `cp ${customSchema} ${outputDir}`,
                `cp ${customResolvers} ${outputDir}`,
              ]
            },
          },
        },
      }
```

The lambda bundle looks like:

<img width="364" alt="Screenshot 2021-10-04 at 10 57 28" src="https://user-images.githubusercontent.com/245131/135814375-7ea9478f-cbe5-413f-a710-3f17a94d2e82.png">

The prisma client is being generated, and prisma-appsync and prisma and @prisma/client should all be being bundled by esbuild. This was working okay before I switch to ES modules, so I'm trying to diagnose what is missing. 

Since esbuild is bundling the generated prisma-appsync client I'd assume it would include the injected config. It shouldn't be getting it from the layer; there is no prisma-appsync stuff on the layer right now.

**Comment by maoosi** [comment]
> The prisma client is being generated, and prisma-appsync and prisma and @prisma/client should all be being bundled by esbuild. This was working okay before I switch to ES modules, so I'm trying to diagnose what is missing.

I'm not 100% sure to understand your full workflow here. I’d suggest to update your NodejsFunctions props with the below and see if that fixes your issue. If not, then please share a reproduction repo and I'll try have a look when I have a bit of free time.

```typescript
{
    bundling: {
        nodeModules: ['prisma', '@prisma/client', 'prisma-appsync'],
        environment: { NODE_ENV: 'production' },
        commandHooks: {
            beforeBundling(inputDir: string, outputDir: string): string[] {
                const prismaSchema = path.join(inputDir, 'packages', 'repo', 'prisma', 'schema.prisma')
                const customSchema = path.join(path.dirname(prismaSchema), 'platform-resolvers.gql')
                const customResolvers = path.join(path.dirname(prismaSchema), 'platform-resolvers.yaml')

                return [
                    `cp ${prismaSchema} ${outputDir}`,
                    `cp ${customSchema} ${outputDir}`,
                    `cp ${customResolvers} ${outputDir}`,
                ]
            },
            beforeInstall() => [],
            afterBundling() {
                return [
                    `npx prisma generate`,
                    'rm -rf node_modules/@prisma/engines', 
                    'rm -rf node_modules/@prisma/client/node_modules', 
                    'rm -rf node_modules/.bin', 
                    'rm -rf node_modules/prisma',
                    'rm -rf node_modules/prisma-appsync'
                ]
            }
        }
    }
}
```

NodejsFunctions will first run the beforeBundling function first (so this is where you are telling the CDK to copy your Prisma schema file at the right place), then it will run `npm install` automatically (and therefore create a fresh install of your dependencies including `prisma` and `prisma-appsync`), then the afterBundling function will run last, which is where you need to run `npx prisma generate` and delete unnecessary files from your bundle after this is done.

**Comment by revmischa** [comment]
Thanks for your patience and explanations. I tried the above and had the same issues. I'm not sure I understand the purpose of setting `prisma-appsync` as a `nodeModules` because the version freshly generated here doesn't contain `PRISMA_APPSYNC_GENERATED_CONFIG` to begin with, and then it's deleted in `afterBundling()`. 

After spending 10 hours on this today I believe I have an idea of what happened. When I switched to ESM to get tree shaking working, it worked and eliminated the generated prisma appsync client from my bundle because I'm not importing it. 
However trying to import the generated `client/index.js` file is really problematic when my project is using `"type": "module"`. I tried so hard but could not get the magic combination of tsconfig and package settings to import the generated commonjs file inside my ESM project. I am going to keep trying to figure out how to do this because I assume I need to actually import the generated client somewhere so that the version with `PRISMA_APPSYNC_GENERATED_CONFIG` in the file gets bundled with my lambda.

Does that sound like I'm on the right track at all?

**Comment by maoosi** [comment]
> I'm not sure I understand the purpose of setting prisma-appsync as a nodeModules because the version freshly generated here doesn't contain PRISMA_APPSYNC_GENERATED_CONFIG to begin with, and then it's deleted in afterBundling().

The `prisma-appsync` package is only needed to run `npx prisma generate`, assuming you have the below code inside your `schema.prisma` file:

```prisma
generator appsync {
    provider = "prisma-appsync"
}
```

During generation, Prisma-AppSync Generator will use your Schema as reference to output a TypeScript Client (plus other files required to deploy your AppSync GraphQL API on AWS) inside a `generated/prisma-appsync` directory. This generated folder is critical for your Lambda function to run properly. You can see an example Lambda Function [here](https://prisma-appsync.vercel.app/guides/installation.html#%F0%9F%91%89-bonus-sample-lambda-function), in case you are not using the provided boilerplate.

The top line `import { PrismaAppSync } from './prisma/generated/prisma-appsync/client'` is importing the generated Prisma-AppSync Client inside the Lambda Function, then using it to parse the Event received from AppSync and return a response to GraphQL queries. If you open the file `generated/prisma-appsync/client/index.js` after running `npx prisma generate`, the very first thing you should see is `process.env.PRISMA_APPSYNC_GENERATED_CONFIG="...`.

Once your `generated/prisma-appsync` directory has been created, you can safely delete the `node_modules/prisma-appsync` directly, as it will not be needed anymore.

Does that help?

**Comment by revmischa** [comment]
Thanks! Really appreciate your patience and explanation. I think I'm clear on the need to import the generated client, my nightmare was coming from the fact I switched to using ES modules and needed to import commonjs (the generated client) from within my ESM project. 

The magic I needed was to add a `package.json` file in the generated client dir with `"type": "commonjs"` and then I was able to happily import it into my project. esbuild just bundles the entire `client.js` in the lambda bundle sadly, but one day when prisma and prisma-appsync support ESM it could be a bit smaller. Not a dealbreaker.

<img width="1776" alt="Screenshot 2021-10-05 at 20 03 51" src="https://user-images.githubusercontent.com/245131/136069422-38e4f435-7281-4bd0-a822-2d9b359257c6.png">

Anyway with ESM+esbuild bundling I'm happily able to run prisma-appsync in lambda with the following setup:

```ts
{
        memorySize: 1536,
        timeout: Duration.seconds(30),

        environment: { NODE_ENV: "production" },

        bundling: {
          commandHooks: {
            beforeInstall: () => [],
            afterBundling: () => [],
            beforeBundling(inputDir: string, outputDir: string): string[] {
              const prismaSchema = path.join(inputDir, "packages", "repo", "prisma", "schema.prisma")
              const customSchema = path.join(path.dirname(prismaSchema), "platform-resolvers.gql")
              const customResolvers = path.join(path.dirname(prismaSchema), "platform-resolvers.yaml")

              return [
                `cp ${prismaSchema} ${outputDir}`,
                `cp ${customSchema} ${outputDir}`,
                `cp ${customResolvers} ${outputDir}`,
              ]
            },
          },
        },
      }
```

And it works swimmingly. Thanks again for your help. We're big fans of this module and hope it continues to develop.

**Comment by maoosi** [comment]
That's great to hear! Thanks for sharing on this, as it might help anyone trying to do the same in the future.

Will definitely continue to develop the Generator. I should be able to release a big update next month, will lots of new features!
