### ISSUE TITLE
Runtime.HandlerNotFound: index.main is undefined or not exported

### ISSUE THREAD

**Issue by panzerchris** [maoosi/prisma-appsync#33]
I followed the installation guide including steps 5 & 6 outlined here:
https://prisma-appsync.vercel.app/guides/installation.html

I'm using Prisma 3.7 and followed their quickstart guide for TypeScript, combined with MySQL for the RDS. 

I successfully generated everything and deployed the application with CDK AppSync but receive this error when running queries:
```Runtime.HandlerNotFound: index.main is undefined or not exported```

Any idea what may be lacking?

**Comment by panzerchris** [comment]
Having dug into this further, I missed the original note in the readme about support for Prisma 2.x. When I downgraded to 2.3.03 this generated and deployed no problem. I'm leaving this as a note for anyone else that encounters the same issue.

**Comment by maoosi** [comment]
Thanks for reporting! There is some big work underway to support the latest versions of Prisma and improve Prisma-AppSync usage. Should be ready for release in Q1.
