### ISSUE TITLE
Not Authorized error when attempting to connect relational data

### ISSUE THREAD

**Issue by panzerchris** [maoosi/prisma-appsync#34]
I am generating an AppSync api for a schema that contains contacts, tags, and a many-to-many relationship table. A contact can have multiple tags. Tags can be on multiple contacts. I largely followed [this Prisma guide](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#explicit-many-to-many-relations) to set up an explicit many-to-many relation between tags and contacts.

```
model Contact {
  id                    Int                             @id @default(autoincrement())
  name                  String
  tags                  TagsOnContacts[]
}

model Tag {
  id                Int                 @id @default(autoincrement())
  name              String              @unique @db.VarChar(45)
  color             String              @db.VarChar(7)
  contacts          TagsOnContacts[]
}

model TagsOnContacts {
  contactId  Int
  contact    Contact         @relation(fields: [contactId], references: [id])
  tagId      Int
  tag        Tag             @relation(fields: [tagId], references: [id])
  assignedAt DateTime        @default(now())
  assignedBy String?

  @@id([contactId, tagId])
}
```

However, when I attempt to connect the data using a query like this, I receive a permission error. Do you know what I might be doing wrong?

```
mutation MyMutation {
  updateContact(
		data: { tags: {connect: {contactId: 10, tagId: 4}} },
		where: {id: 10}
	) {
    id
  }
}
```

```
{
	"data": {
		"updateContact": null
	},
	"errors": [
		{
			"path": [
				"updateContact"
			],
			"data": null,
			"errorType": "Unauthorized",
			"errorInfo": null,
			"locations": [
				{
					"line": 2,
					"column": 3,
					"sourceName": null
				}
			],
			"message": "Not Authorized to access updateContact on type Mutation"
		}
	]
}
```

I'm using an API key in AppSync for authorisation. I can create and update contacts and tags, but I am unable to connect one to the other without the authorisation error.

**Comment by maoosi** [comment]
This error seem related to [AppSync Authorization modes](https://prisma-appsync.vercel.app/guides/securing-api.html#%F0%9F%91%89-appsync-authorization-modes). Make sure to define a `default` authorization in your `schema.prisma` file, such as:

```prisma
generator appsync {
    provider = "prisma-appsync"
    directiveAlias_default = "@aws_api_key"
}
```

The above will automatically apply the [@aws_api_key](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#using-additional-authorization-modes) authorization mode to all Prisma-AppSync generated Types.
