### ISSUE TITLE
Case Insensitive Search 

### ISSUE THREAD

**Issue by urbentom** [maoosi/prisma-appsync#35]
Hi, 

We are in the process of building search functionality on our app and we have noticed ( at least when using Mongo as the DB) that the queries are not case insensitive.

To get this to work we have looked at enabling [collation](https://docs.mongodb.com/manual/core/index-case-insensitive/) table wide on MongoDB which had no affect when querying via AppSync. This is probably cause [Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#mongodb-provider) uses Regex to query MongoDB and that the collation is more for the full string compare. 

After looking further into it, it seems that Prisma needs `mode` to be passed through as part of the where filters. The relevant docs can be found [here](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#case-insensitive-filtering). 

Has anyone else been able to get a case insensitive search working with MongoDB using prisma-appsync? If not is this something we can integrate in this package?

**Comment by urbentom** [comment]
It would be nice in the query itself to be able to add which fields are case intensive and which are not but I assume that would be a massive pain to get the generation to work?

After having a little poke around the code and noticed that the `args.where` are being passed through to the Prisma query. As a short term fix do you think we could use the `beforeResolve` hook to mutate the where object to add the `mode` parameter?

**Comment by maoosi** [comment]
Instead of `beforeResolve` I would suggest leveraging the [Prisma Client Middleware](https://www.prisma.io/docs/concepts/components/prisma-client/middleware) component.

Example (not tested):

```typescript
// initialise prisma-appsync client
const app = new PrismaAppSync({ /****/ })

// before calling `await app.resolve()`
app.prisma.$use(async (params, next) => {
  if (params.model == ‘User’ && params?.args?.where?.email) {
    params.args.where.email.mode = ‘insensitive’
  }

  return next(params)
})
```

Adding proper support for `mode` is [planned](https://github.com/maoosi/prisma-appsync/projects/1#card-63459528), but I don’t have an ETA for it yet.
