### ISSUE TITLE
Relation type value's that are not PascalCase causes error `Unknown type ... Did you mean ...`

### ISSUE THREAD

**Issue by ryparker** [maoosi/prisma-appsync#39]
The error seems to be throwing when [prettier is attempting to parse the generated graphql schema](https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/src/generator/compiler.ts#L111-L118).

It looks like the prettier error is caused by the GraphQL schema's input field values not being PascalCase.

Here's an example error:

```sh
Unknown type "github_issue_labels_v3CreateInput". Did you mean "GithubIssueLabelsV3CreateInput", "GithubIssueLabelsV3UpdateInput", "GithubIssueLabelsV3CreateManyInput", "GithubIssueLabelsV3OrderByInput", or "GithubIssueLabelsV3UpsertInput"?
```

Here's where the parser failed in the graphql schema
```graphql
input GithubIssuesV3GithubIssueLabelsV3CreateRelationsInput {
    create: [github_issue_labels_v3CreateInput]
    connect: [github_issue_labels_v3WhereUniqueInput]
    connectOrCreate: [github_issue_labels_v3ConnectOrCreateInput]
}
```

However there is no `github_issue_labels_v3CreateInput` in the schema but there is a `GithubIssueLabelsV3CreateInput` which I believe is the correct value it should be using.

```graphql
input GithubIssueLabelsV3CreateInput {
    issue_id: Int!
    repo_id: Int!
    label: String!
    github_issues_v3: GithubIssueLabelsV3GithubIssuesV3CreateRelationsInput!
    github_repo_v3: GithubIssueLabelsV3GithubRepoV3CreateRelationsInput!
}
```

[Here in the template is where the problem seems to be generated from.](https://github.com/maoosi/prisma-appsync/blob/feae1a466490c610a1f2d58a9cfb85971114ac13/src/generator/templates/schema.gql.njk#L158-L195)

Interestingly enough I noticed that the `GithubIssueLabelsV3CreateInput` is being used properly when referenced in the template as `{{ model.name }}` but the snake_case version occurs when using `{ field.relation.type }}`.

Working when template uses `{{ model.name }}` as used here:
```njk
input {{ model.name }}UpsertInput {
        create: {{ model.name }}CreateInput!
        update: {{ model.name }}UpdateInput!
    }
```
Which generates appropriate PascalCase output:
```graphql
input GithubIssueLabelsV3UpsertInput {
    create: GithubIssueLabelsV3CreateInput!
    update: GithubIssueLabelsV3UpdateInput!
}
```

Breaking when template uses `{{ field.relation.type }}` as used here:
```njk
input {{ field.relation.name }}CreateRelationsInput {
                {% if field.relation.kind === "one" -%}
                create: {{ field.relation.type }}CreateInput
                connect: {{ field.relation.type }}WhereUniqueInput
                connectOrCreate: {{ field.relation.type }}ConnectOrCreateInput
                {% else  -%}
                create: [{{ field.relation.type }}CreateInput]
                connect: [{{ field.relation.type }}WhereUniqueInput]
                connectOrCreate: [{{ field.relation.type }}ConnectOrCreateInput]
                {% endif -%}
            }
```
Which generates the unexpected snake_case output:
```graphql
input GithubIssuesV3GithubIssueLabelsV3CreateRelationsInput {
    create: [github_issue_labels_v3CreateInput]
    connect: [github_issue_labels_v3WhereUniqueInput]
    connectOrCreate: [github_issue_labels_v3ConnectOrCreateInput]
}
```

**Comment by ryparker** [comment]
Fix here https://github.com/maoosi/prisma-appsync/pull/38

**Comment by maoosi** [comment]
Thanks again @ryparker! Both your PR have been implemented as part of the latest release: https://github.com/maoosi/prisma-appsync/releases/tag/1.0.0-rc.1
