### ISSUE TITLE
cdk v2

### ISSUE THREAD

**Issue by ameerulislam** [maoosi/prisma-appsync#41]
Do you have plans converting this repo to Cdk v2 ?

**Comment by maoosi** [comment]
@ameerulislam yes, big work in progress on this repo, including CDK v2 and lots of new features. If you are curious about what’s coming next, you can have a look at the [wip changelog](https://maoosi.notion.site/1-0-0-rc-1-a3e4b96df8d04515a17114ff9093ba16).

**Comment by ameerulislam** [comment]
Thank you for the update and keep up the good work!

**Comment by ameerulislam** [comment]
I'm currently use parameter store instead of PRISMA_CONNECTION_URL from cdk env file. For DB connection. What suggestion do you have for me?

**Comment by maoosi** [comment]
I suggest you avoid reading values from the Parameter Store at runtime (directly from within the Lambda Function), as this might incur [additional charges](https://www.amazonaws.cn/en/systems-manager/pricing/) and there are throughput limits in place.

Instead, I suggest you read the value stored in Parameter Store [from inside your CDK files](https://docs.aws.amazon.com/cdk/v2/guide/get_ssm_value.html), and inject it as an Environment variable for the Lambda Function.

**Comment by ameerulislam** [comment]
Thank you for the insight. Yes I'm trying to add it in cdk file where you define the environment for lambda. I believe that will extract the parameter while building the lambda function. However, I'm still struggling to add the right code since I'm not an expert in writing cdk yet. Having problem with the scope and constructs.
