### ISSUE TITLE
Upcoming rename of `@prisma/sdk` to `@prisma/internals` with Prisma 4

### ISSUE THREAD

**Issue by janpio** [maoosi/prisma-appsync#42]
Hey,

Jan from Prisma Engineering here.
 
Quick heads up that we will soon rename our `@prisma/sdk` package to `@prisma/internals` with Prisma 4, which we plan to release on June 28th (soon!). 

The `@prisma/sdk` package was meant as an Prisma internal package only, but somehow it leaked out over time and is now used across all kinds of tools - including yours of course 😄

With the rename of the Npm package we want to make it clearer that we can not give any API guarantees for `@prisma/internals`, might need to introduce breaking changes to the API from time to time and will not follow semantic versioning (breaking changes only in major upgrade) with it. We think that it is better communicated with `internals` than with `sdk`.
With Prisma 4, besides the package name nothing should change though.

Additionally it would be super helpful if you could help us gain an understanding where, how and why you are using `@prisma/sdk` (soon `@prisma/internals`, remember 😀) to achieve, what exactly. We want to cleanup that package and your feedback will be valuable to us to define a better API.

Looking forward to your feedback.

Best
Jan & your friends at Prisma

PS: Are you using `Prisma.dmmf` from `import { Prisma } from '@prisma/client'` in your code somewhere by chance? That will also change soon and not include the `Prisma.dmmf.schema` sub property. Instead you can use `getDmmf` from `@prisma/internals` moving forward.

**Comment by maoosi** [comment]
Hey @janpio, thanks for letting me know!

Removing `@prisma/sdk` entirely from Prisma-AppSync will not be an issue, as I’m only using it for its `parseEnvValue` function (which I was planning to remove in the next coming release). I am also not using `Prisma.dmmf` from `@prisma/client` anywhere.

Prisma-AppSync is mainly reliant on `generatorHandler` and `DMMF` exported from `@prisma/generator-helper` package, as well as the `GeneratorOptions` available from the `generatorHandler :: onGenerate` handler. I am reading the `dmmf.datamodel` property from there.

Any changes planned on the above?

**Comment by Jolg42** [comment]
Note: You can try prisma packages on the `dev` tag on npm, like `@prisma/internals@3.16.0-dev.84`

**Comment by maoosi** [comment]
@Jolg42 Thanks! Will look into it.
