### ISSUE TITLE
Generator for v2

### ISSUE THREAD

**Issue by cipriancaba** [maoosi/prisma-appsync#44]
Great job on the library, your approach makes the most sense from all the research I've done

I saw the progress on the next version which looks really great, was wondering if there's a generator we can use with the preview version eg `yarn create prisma-appsync-app@preview`

Only thing I'm missing is the cdk boilerplate, but I assume I can just use the one from the dev branch?

**Comment by maoosi** [comment]
Thanks @cipriancaba! The next version is close to being released. I’m planning on finalising the remaining tasks and documentation writing after I am back from my current holiday.

At this stage, there is no preview command you can use to automate installation - however, you can clone the `maoosi/dev` branch (most up to date) and manually copy files from inside the `packages/boilerplate` directory - which include a CDK file (using aws-cdk v2).

**Comment by cipriancaba** [comment]
Makes sense, that's what I was planning to do.. Thanks for the hard work and enjoy your holiday 

On an unrelated note, is there an option to allow for opt-in generation of crud endpoints os opposed to opt-out? As in, don't want all the models to have cruds, just some of them

**Comment by cipriancaba** [comment]
This was incredibly helpful, using v2 with great success. Amazing job
