### ISSUE TITLE
AWS_LAMBDA Authorization

### ISSUE THREAD

**Issue by DevoteamQinzhu** [maoosi/prisma-appsync#45]
First of all, thanks for sharing this library.

Is that possible to enable AWS_LAMBDA Authorization?

**Comment by maoosi** [comment]
@loxmys yes! Will add this to the next release.

**Comment by maoosi** [comment]
Released in [v1.0.0](https://github.com/maoosi/prisma-appsync/releases/tag/v1.0.0).
