### ISSUE TITLE
Issue with generated GraphQL input `CreateInput` when using `@default(uuid())` inside Prisma Schema

### ISSUE THREAD

**Issue by StephanDecker** [maoosi/prisma-appsync#62]
Great work! We used the beta version and that worked smoothly. After updating to the RC it seems that ID fields that are auto-populated by the database are mandatory when executing the create* mutations. That means: When creating a record I have to handover the id although the id is autogenerated in the database:
Here is the example:

schema.prisma:
```...
model Phase {
    id            String          @id @default(uuid())
    name          String          @unique
}
...?
```

generated schema.gql (using beta):
```graphql
input PhaseCreateInput {
	name: String!
}
```

generated schema.gql (after upgrade to RC):
```graphql
input PhaseCreateInput {
    id: String!
    name: String!
}
```
Could you fix that? Thanks!

**Comment by maoosi** [comment]
Fix release in [1.0.0-rc.3](https://github.com/maoosi/prisma-appsync/releases/tag/1.0.0-rc.3).
