### ISSUE TITLE
Not authorized on custom resolvers

### ISSUE THREAD

**Issue by cipriancaba** [maoosi/prisma-appsync#73]
Going a bit crazy with the custom resolvers. Trying to do a simply query with an api key and it's failing. Tried adding the @aws_api_key on the types as well, but still failing. When using cognito user pool it works as expected

This happens on deployed version only

@maoosi would greatly appreciate it if you could point me in the right direction here

```
query MyQuery {
  healthcheck {
    db
    status
  }
}
```

This is the result
```
{
  "data": {
    "healthcheck": null
  },
  "errors": [
    {
      "path": [
        "healthcheck",
        "db"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 3,
          "column": 5,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access db on type HealthcheckStatus"
    },
    {
      "path": [
        "healthcheck",
        "status"
      ],
      "data": null,
      "errorType": "Unauthorized",
      "errorInfo": null,
      "locations": [
        {
          "line": 4,
          "column": 5,
          "sourceName": null
        }
      ],
      "message": "Not Authorized to access status on type HealthcheckStatus"
    }
  ]
}
```

And the handler + shield:
```
return await client.resolve<
    | 'healthcheck'
  >({
    event,
    shield: ({}: QueryParams) => {
      return {
        '**': {
          rule: true,
          reason: ({ model }) =>
            `${model} access is restricted to logged-in users.`,
        },
      }
    },
    resolvers: {
      healthcheck: async ({ args: _, prismaClient }: QueryParamsCustom) => {
        try {
          await prismaClient.$queryRaw`SELECT 1`
          return {
            status: true,
            db: 'OK',
          }
        } catch (e) {
          return {
            status: false,
            db: (e as any).message,
          }
        }
      },
    },
  })
```

Custom schema
```
type HealthcheckStatus
  @aws_api_key
  @aws_cognito_user_pools(cognito_groups: ["admins", "superadmins"]) {
  status: Boolean!
  db: String!
}
```

```
extend type Query {
healthcheck: HealthcheckStatus
    @aws_api_key
    @aws_cognito_user_pools(cognito_groups: ["admins", "superadmins"])
}
```

**Comment by maoosi** [comment]
Hey @cipriancaba, I can't see anything wrong with what you just shared. Any chance you'd have a reproduction repo handy with your entire schema and custom resolver files? Otherwise, I can try to replicate the issue on my end over the weekend.

**Comment by cipriancaba** [comment]
I ended up removing the shield validation and that seemed to do the trick. Not ideal, since will need to add it back soon for user authorization

In general, it feels like working with custom resolvers is a bit cumbersome. For example, spent hours trying to figure out why my custom resolver wasn't returning the proper data, just to realise that I forgot to add it to the custom-resolvers.yaml file. It was obviously working fine locally.

I think the following areas could benefit some improvements:
- More documentation around custom resolvers. I think that any real world use case would need to have custom resolvers
- Clarify how the custom directives should work in custom-schema (eg, do you need to add `@aws_api_key` on custom type? )
- Simplify the process of creating custom resolvers. It's just too easy to misconfigure them atm. Maybe we can potentially generate at least the custom-schema.yml ?
- Improve the `QueryParamsCustom` interface to allow for generic type params (I actually have a PR for it) so it's easier to work with args

I understand that maybe this might not be the focus of the library, but this would definitely make it easier to use and become the swiss army knife of graphql backends
