### ISSUE TITLE
How to extend models/types with computed values?

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#75]
Hi,

I tried following the "extending the API" guide on the documentation, only applying it to one of the generated types, like so:

```graphql
extend type User {
	test: Int
}
```
```yaml
- typeName: User
  fieldName: test
  dataSource: prisma-appsync
```
```js
resolvers: {
	test: async ({ args, prismaClient }) => {
		return 1;
	},
},
```

However I get given an error by Prisma Client about a validation error, talking about an unknown field `test`. I imagine this is far from the best way to do this anyway, but I was wondering if there was any good way to extend types with computed fields which could use other fields and relationships as data for JavaScript to work with?

**Comment by maoosi** [comment]
Hey @Tenrys, sorry for the confusion! I should probably make that clearer in the docs, but creating custom resolvers for individual fields isn't possible with Prisma-AppSync.

You can only create custom resolvers for top-level Queries, Mutations and Subscriptions. Such as:

```gql
type Query {
  test: Int
}
```

```yml
- typeName: Query
  fieldName: test
  dataSource: prisma-appsync
```

```tsx
resolvers: {
  test: async () => 1
},
```

That said, one other way to achieve this (if you really need to) is creating a [Prisma Middleware](https://www.prisma.io/docs/concepts/components/prisma-client/middleware):

```gql
extend type User {
  test: Int
}
```

```tsx
// Instantiate Prisma-AppSync Client
const prismaAppSync = new PrismaAppSync()

// Custom Prisma middleware
prismaAppSync.prismaClient.$use(async (params, next) => {
  const model = 'User'
  const field = 'test'
  const fieldResolver = () => 1
  
  // remove field from query (otherwise prisma will fail, as the field doesn't exist in db)
  if (params.model === model && params?.args?.select?.[field])
    delete params.args.select[field]
  
  // run query
  const result = await next(params)
  
  // inject field in result
  if (params.model === model) {
    if (Array.isArray(result))
      return result.map(r => ({ ...r, [field]: fieldResolver() }))
    else
      return { ...result, [field]: fieldResolver() }
  }

  return result
})

// Lambda handler (AppSync Direct Lambda Resolver)
export const main = async (event: AppSyncResolverEvent<any>) => {
  return await prismaAppSync.resolve({ event })
}
```

Not as clean, but it should work.

**Comment by sjerratsch** [comment]
you can actually achieve this, when you do the following:

1) Get your schema right. Extend the type in the schema with the correct types
2) Use the prisma client extension to add a computed field to a model
3) set  prismaAppSync.prismaClient to the extended client instead of the original one
4) use the 'before:**' hook to remove the prismaArgs.select property entirely when a computed property is selected, otherwise it won't be available in the result (see prisma docs)
