### ISSUE TITLE
Error in docs: Fine-grained access control example using wrong syntax

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#79]
https://github.com/maoosi/prisma-appsync/blob/8a93d2f7894b5dd56f4b76ab2b3758aedbd20bfd/docs/advanced/securing-api.md?plain=1#L153
https://github.com/maoosi/prisma-appsync/blob/8a93d2f7894b5dd56f4b76ab2b3758aedbd20bfd/docs/advanced/securing-api.md?plain=1#L178

After further inspection, it seems like the paths are more like the log on the bottom, rather than in the format the docs are instructing.

![image](https://user-images.githubusercontent.com/3979239/207905422-8e3c75af-8466-46c7-9a5e-3a4003f69ddd.png)

I've looked at the code for a little bit and it seems like the aliasing is not used at all for the shield / guard feature, relying more on match the actual GraphQL query paths, which is not very flexible.

It would be nice also for nested writes / reads to call the top level guards, e.g: I have a guard on `createPhone`, but I am creating a phone number through `createUser/phone/**`. Only that path will be checked, and not the more basic one. Ideally, it would be checked before the nested path.

https://github.com/maoosi/prisma-appsync/blob/a874bc5ce48edef53014b9015c0dda97f4884335/docs/advanced/securing-api.md?plain=1#L169

Is it possible to access the `authorization` and/or `identity` fields from within a Prisma middleware somehow?

**Comment by maoosi** [comment]
Thanks @Tenrys! The documentation has been updated with the new syntax: https://prisma-appsync.vercel.app/advanced/securing-api.html#%F0%9F%91%89-fine-grained-access-control

In regards to protecting nested fields, you could do something like this:

```tsx
return await prismaAppSync.resolve({
  event,
  shield: () => {
    return {
      '**/create*/phone{,/**}' {
        rule: false
      },
    }
  },
})
```

Here is an online tool to interactively create rules and check them against paths:
https://globster.xyz/?q=**%2Fcreate*%2Fphone%7B%2C%2F**%7D&f=%2FcreatePhone%2Fphone%2C%2FcreateUser%2Fphone
