### ISSUE TITLE
Issue: Local dev server reads `undefined` when using nested arrays in query

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#81]
With this Prisma schema:

```prisma
model Customer {
  uuid      String   @id @default(uuid())
  firstName          String        @default("")
  lastName           String        @default("")
  email              String        @unique
  phoneUuid          String
  phone              Phone         @relation(fields: [phoneUuid], references: [uuid])
}
```

And this query:

```graphql
query MyQuery {
  listCustomers(where: { 
    OR: [
      { firstName: { contains: "bla" } }, 
      { lastName: { contains: "bla" } }
    ] 
  ) {
    uuid
    firstName
    lastName
    email
    phone {
      number
    }
  }
}
```

GraphQL Yoga seems to be receiving the parameters incorrectly, returning an empty result since Prisma can't understand the request:

![image](https://user-images.githubusercontent.com/3979239/209562520-497ba328-1f61-4449-85b5-aa9a903bea67.png)

```json
{
    "data": {
        "listCustomers": []
    }
}
```

I've tried deploying onto AppSync itself and the query does function over there, so I think it may be some slip-up related to the development server.

**Comment by maoosi** [comment]
Fix will be released as part of `1.0.0-rc.5`.
