### ISSUE TITLE
Feature: Add support for `is`, `isNot` relation filters

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#93]
They seem to be missing in the currently generated GraphQL types, I'm not certain when they are and aren't available, but I think it would be nice to have the option to use them, maybe.

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#is

I'm not sure if it would be as easy as modifying the schema generator template. For now I'll settle with `some`, I may take a look myself later

**Comment by maoosi** [comment]
Both `is` and `isNot` filters were removed from `1.0.0-rc.2` ([see full changelog](https://prisma-appsync.vercel.app/changelog/1.0.0-rc.2.html)) in favour of the newest [Fluent API syntax](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#fluent-api).

This (removed):

```gql
query {
 listPosts(
  where: {
   author: { is: { username: "xxx" } }
  }
 ) {
  title
  author { username }
 }
}
```

Is equivalent to this (supported):

```gql
query {
 listPosts(
  where: {
   author: { username: { equals: "xxx" } }
  }
 ) {
  title
  author { username }
 }
}
```

Supporting both syntaxes simultaneously could be possible using the below Schema:

```gql
input UserScalarsWhereInput {
  # ...
  author: String
}

input PostWhereInput {
  # ...
  author: UserWhereInput
  is: UserScalarsWhereInput
  isNot: UserScalarsWhereInput
}
```

However, I'm thinking it would add (unnecessary?) complexity to detect and prevent using both syntaxes simultaneously within a single query.

Unless there is a use case in which the Fluent API syntax wouldn't allow doing the same as with `is` and `isNot`?

**Comment by Tenrys** [comment]
I was mostly thinking about how to check whether or not a one-to-one relationship exists. I know the equivalent would be `some: {}` for one-to-many.

**Comment by maoosi** [comment]
Would you have an example query to share (if you were to do it with the Prisma Client directly)?

**Comment by Tenrys** [comment]
```prisma
model Valuation {  
  ...
  estate      Estate?
  ...
}

model Estate {
  ...
  valuationUuid String     @unique
  valuation     Valuation  @relation(fields: [valuationUuid], references: [uuid])
  ...
}
```

```js
const valuations = await client.valuation.findMany({
	where: {
		estate: {
			is: null,
		},
	},
});
```

Maybe there is a better way that I don't know of.

**Comment by maoosi** [comment]
Another way to achieve the same would be:

```gql
query {
  listValuations(
    where: {
      estateUuid: { equals: null }
    }
  ) {
    id
  }
}
```

In theory this should work, though I've just tested it on my local machine - and it seems the event parser is transforming `null` values into `undefined`.

```gql
arguments: {
  where: {
    estateUuid: {
      not: undefined # this should be null
    }
  }
}
```

Can please try and let me know if see the same issue on your end?

**Comment by Tenrys** [comment]
Well, I have the foreign key on the side of the estate which refers to the valuation, so I can't check the exact same way.

I've tried a few different ways, but it doesn't seem to do much, e.g:

![image](https://user-images.githubusercontent.com/3979239/211780839-1a1d7e7c-361c-4727-967c-6e829987941f.png)

**Comment by Tenrys** [comment]
I think it wouldn't hurt to bring back `<Model>RelationFilter` as it is in Prisma, with the same definition as `<Model>WhereInput`, except with those two deleted lines brought back:

https://github.com/maoosi/prisma-appsync/commit/12865a17b85ecfdd89c060ca47c05a999f657b83#diff-0f3118d4d839ee46a643c4a03ad907f78569918a6a3cc248ab072e0e45bcba0aR52-R63

While making sure they do not get overriden, like how Prisma does it:

```ts
export type ValuationWhereInput = {
  AND?: Enumerable<ValuationWhereInput>
  OR?: Enumerable<ValuationWhereInput>
  NOT?: Enumerable<ValuationWhereInput>
  ...
  estate?: XOR<EstateRelationFilter, EstateWhereInput> | null
}

export type EstateRelationFilter = {
  is?: EstateWhereInput | null
  isNot?: EstateWhereInput | null
}
```

**Comment by maoosi** [comment]
There is no proper way to express `OR` or `XOR` in GraphQL, so I don't think it will be possible to emulate `XOR<EstateRelationFilter, EstateWhereInput> | null`.

This is also why `null` filters are causing issues, as you can't write `uuid: StringFilter | null` or `is: EstateWhereInput | null` either with GraphQL. If your model is expecting `uuid: StringFilter` and you give it `null`, it is interpreted as `undefined` and then doesn't work properly when passed to Prisma Client.

That being said, not being able to use `null` filter is problematic - so I will open a new issue and look into ways we can possibly fix it.

**Comment by Tenrys** [comment]
Do you think fixing that issue would then take care of my initial problem and let me filter on one-to-one relationship existence, where the foreign key is not available on the model that is being filtered?

**Comment by maoosi** [comment]
Yes, that's what I'm hopping for.

**Comment by maoosi** [comment]
@Tenrys you can install `prisma-appsync@1.0.0-preview.6.4` and try this:

```gql
query {
  listValuations (
    where: {
      estate: { is: NULL },
    }
  ) {
    uuid
    estate {
      uuid
    }
  }
}
```

Let me know if that solves your issue?

**Comment by Tenrys** [comment]
Works perfect for relationships, however I tried `is` and `isNot` on `Int`, `String`, `Boolean` and came up with validation errors because `is` and `isNot` aren't handled on their filters.

**Comment by maoosi** [comment]
Should work better now if you install `prisma-appsync@1.0.0-preview.6.5` !

- Filtering by `null` on Relations can be done via `is: NULL` and `isNot: null`
- Filtering by `null` on regular fields (String, Boolean, etc) can be done via `isNull: true` and `isNull: false`
- Filtering by `null` on required fields is not possible (e.g. if `title` is required/mandatory it means it can't be `null`)

**Comment by Tenrys** [comment]
A bug I found: if you try to use `is` and `isNot` from `<Model>WhereInput` inside of a `some` or `every`, Prisma throws a validation error.

**Comment by maoosi** [comment]
Thanks @Tenrys! I've created a separate issue: https://github.com/maoosi/prisma-appsync/issues/102
