### ISSUE TITLE
Issue: All fields with `@default(xxx)` should be optional in GraphQL Schema

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#96]
I would expect to be able to omit required fields that have a default value entirely, so that the database can fill them up for me if I choose not to specify them, but it looks like a field is only considered "auto-populated" under very specific conditions:

https://github.com/maoosi/prisma-appsync/blob/aa0816bfa8b2514633a466756c71ed20bbe26093/packages/generator/src/compiler.ts#L669-L678

Shouldn't it just be flagged as such as long as it has a valid `@default` attributes?

**Comment by maoosi** [comment]
Will be release as part of `[1.0.0-rc.6](https://github.com/maoosi/prisma-appsync/milestone/5)`.
