### ISSUE TITLE
Feature: Prisma schema column default values should be reflected in input types

### ISSUE THREAD

**Issue by Tenrys** [maoosi/prisma-appsync#97]
It's a small detail, but being able to see that certain fields can have default values from within a GraphQL IDE (like Apollo Explorer) would be a nice improvement, as per https://stackoverflow.com/a/51567429.

**Comment by maoosi** [comment]
Great suggestion! @all-contributors please add @Tenrys for ideas!

**Comment by maoosi** [comment]
Released in [v1.0.0](https://github.com/maoosi/prisma-appsync/releases/tag/v1.0.0).

**Comment by Tenrys** [comment]
It seems like having an empty string as your default value breaks the schema, since default string values don't have quotes around them. In my fork I made it so default string values are surrounded by blockquotes (`"""`) with the default value escaping the blockquote sequence of characters. (`\"""`)

**Comment by maoosi** [comment]
Thanks for reporting @Tenrys - I've just released a fix with [v1.0.1](https://github.com/maoosi/prisma-appsync/releases/tag/v1.0.1)!
